#This is for lamda plus terraform deploy
#Creator: Sarthak
name: Github Actions For Backend Deploy

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt -t .
          zip -r lambda_backend_code.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRECT_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --aplhanumeric-payment-gateway \
            --zip-file fileb://backend/lambda_backend_code.zip
