#Purpose: Terraform file to deploy the backend code
#Maintainer: Sarthak

name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt -t .
          zip -r lambda_backend_code.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${ secrets.AWS_ACCESS_KEY_ID }
          aws-secret-access-key: ${ secrets.AWS_SECRET_ACCESS_KEY }
          aws-region: ap-south-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --lambda_backend_code \
            --zip-file fileb://backend/lambda_backend_code.zip
